task: "RobotArm_6DOF"

hyperparameters:
  num_envs: 32
  batchsize: 4096
  episodes: 100
  entropy_weight: 0.01
  value_weight: 1.
  ls: 0.0001

  ppo:
    clip_param: 0.2
    gamma: 1.
    gae_lambda: 0.95
    num_minibatches: 4
    rollout_length: 50

