task: "RoeFlux_1d"

hyperparameters:
  batchsize: 32
  episodes: 100
  entropy_weight: 0.01
  value_weight: 1.
  ls: 0.0001

  ppo:
    clip_param: 0.2
    gamma: 1.
    gae_lambda: 0.95
    num_minibatches: 4

