task: "RoeFlux_1d"

hyperparameters:
  num_envs: 32
  batchsize: 4096
  episodes: 5000
  entropy_weight: 0.01
  value_weight: 1.
  ls: 0.00025

  ppo:
    clip_param: 0.2
    gamma: 1.
    gae_lambda: 0.95
    num_minibatches: 4
    rollout_length: 98

